carts/urls.py
from django.urls import path
from .views import cart, add_cart, remove_cart, remove_cart_item, checkout

urlpatterns = [
    path('', cart, name='cart'),
    path('add_cart/<int:product_id>/', add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item, name='remove_cart_item'),
    path('checkout/', checkout, name='checkout'),
]

customkit/urls.py
from django.urls import path
from customkit import views


urlpatterns = [
    path('', views.customkit, name='customkit'),
    path('custom-product/<slug:product_slug>/', views.custom_product_detail, name='custom_product_detail'),
    path('custom_add-to-cart/<int:product_id>/', views.add_cart, name='custom_add_to_cart'),
    path('custom_remove-from-cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='custom_remove_from_cart'),
    path('custom_remove-cart-item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='custom_remove_cart_item'),
    path('custom_cart/', views.cart, name='custom_cart'),
    path('custom_checkout/', views.checkout, name='custom_checkout'),

    path('order/<slug:product_slug>/', views.order_product, name='order_product'),
    path('order/confirmation/<slug:order_number>/', views.order_confirmation, name='order_confirmation'),
    path('calculate_total_price/', views.calculate_total_price, name='calculate_total_price'),

]
    

ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from ecom import views
from accounts import urls as accounts_urls
from store import urls as store_urls
from carts import urls as carts_urls
from orders import urls as orders_urls
from customkit import urls as custom_urls
from youtube import urls as youtube_urls
from django.urls import re_path
from django.conf import settings
from django.views.static import serve
from images import urls as images_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include(accounts_urls)),
    path('store/', include(store_urls)),
    path('cart/', include(carts_urls)),
    path('orders/', include(orders_urls)),
    path('create-your-own/', include(custom_urls)),
    path('tutorials/', include(youtube_urls)),
    path('images/', include(images_urls)),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),



]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import place_order
# from .views import payments
# from .views import order_complete
urlpatterns = [
    path("place_order/", place_order, name="place_order"),
    # path("payments/", payments, name="payments"),
    # path("order_complete/", order_complete, name="order_complete"),

]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id



class Order(models.Model):
    STATUS = (
        ("New", "New"),
        ("Accepted", "Accepted"),
        ("Completed", "Completed"),
        ("Cancelled", "Cancelled"),
    )
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, null=True, blank=True
    )
    order_number = models.CharField(max_length=20)
    
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default="New")
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def full_address(self):
        return f"{self.address_line_1} {self.address_line_2}"

    def __str__(self):
        return self.first_name


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, null=True, blank=True
    )
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

customkit/forms.py
from django import forms
from .models import CustomOrder

class CustomOrderForm(forms.ModelForm):
    class Meta:
        model = CustomOrder
        exclude = ['order_number', 'tax', 'order_total']
        fields = [
            'quantity',
            'stuff',
            'sizes',
            'order_number',
            'first_name',
            'last_name',
            'phone',
            'email',
            'address_line_1',
            'address_line_2',
            'country',
            'state',
            'city',
            'order_note',
            'status',
            'ip',
            'is_ordered',
        ]
        widgets = {
            'order_number': forms.HiddenInput(),
            'status': forms.HiddenInput(),
            'ip': forms.HiddenInput(),
            'is_ordered': forms.HiddenInput(),
            'order_note': forms.Textarea(attrs={'rows': 2, 'placeholder': 'Order Note', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(CustomOrderForm, self).__init__(*args, **kwargs)
        # No need to make 'tax' or 'order_total' read-only here

orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'email', 'address_line_1', 'address_line_2',
                  'country', 'state', 'city', 'order_note']

carts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist



# usa a session id para criar o carrinho
def _cart_id(request):  # private function
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):  # adiciona item ao carrinho e adiciona quantidade
    current_user = request.user  # pega da requisição o usuario logado
    product = Product.objects.get(id=product_id)  # pega o produto pelo id

    # add to cart if the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product,
                                                      variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')

    # add to cart if user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product,
                                                      variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        # product = Product.objects.get(id=product_id)  # pega o produto pelo id
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  # busca o carrinho pela session da request
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            ex_var_list = []  # existing variation list
            id = []  # id list of the variations
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            print(ex_var_list)
            if product_variation in ex_var_list:
                # increase cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1  # soma 1 na quantidade de produto
                item.save()
            else:
                # create new cart item
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):  # diminui a quantidade no carrinho
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):  # remove o item do carrinho
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        tax = (2*total)/100  # aplicar regra de imposto correta aki
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass  # ignora
    context = {'total': total,
               'quantity': quantity,
               'cart_items': cart_items,
               'tax': tax,
               'grand_total': grand_total,
               }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        tax = (2 * total) / 100  # aplicar regra de imposto correta aki
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass  # ignora
    context = {'total': total,
               'quantity': quantity,
               'cart_items': cart_items,
               'tax': tax,
               'grand_total': grand_total,
               }
    return render(request, 'store/checkout.html', context)

templates/customkit/order_form.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

<head>
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<meta name="keywords" content="MediaCenter, Template, eCommerce">
<meta name="robots" content="all">
<title>{% block title %}{% endblock title %} - Tie</title>

<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

<!-- Customizable CSS -->
<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/blue.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/owl.transitions.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/rateit.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/bootstrap-select.min.css' %}">
<link href="{% static 'assets/css/lightbox.css' %}" rel="stylesheet">

<!-- Icons/Glyphs -->
<link rel="stylesheet" href="{% static 'assets/css/font-awesome.css' %}">

<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Barlow:200,300,300i,400,400i,500,500i,600,700,800" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body class="cnt-home">



{% include "includes/navbar.html" %}





<!-- ============================================== HEADER : END ============================================== -->
<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="#">Home</a></li>
				<li class='active'>Checkout
					
				</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->






<div class="body-content">
	<div class="container">
		<form method="post" enctype="multipart/form-data" >
			{% csrf_token %}


			{{form.order_number}}
			{{form.status}}
			{{form.ip}}
			{{form.is_ordered}}

		<div class="checkout-box ">
			<div class="row">
<div class="col-xs-12 col-sm-6 col-md-6 rht-col">
<div class="panel-group checkout-steps" id="accordion">
						<!-- checkout-step-01  -->
<div class="panel panel-default checkout-step-01">

	<!-- panel-heading -->
		<div class="panel-heading">
    	<h4 class="unicase-checkout-title">
	        <a data-toggle="collapse" class="" data-parent="#accordion" href="#collapseOne">
	          <span>1</span>Checkout Method
			</a>
	     </h4>
    </div>
    <!-- panel-heading -->

	<div id="collapseOne" class="panel-collapse collapse in">

		<!-- panel-body  -->
	    <div class="panel-body">
			<div class="row">		
                <div class="col-md-12 col-sm-12">
                    <h4 class="checkout-subtitle">Order Details</h4>
                    <div class="row">
                      
                        <div class="form-row">
                            <div class="col-md-6 form-group">
                                <label for="">Quantity</label>
                                {% render_field form.quantity type="number" placeholder="Quantity" class="form-control" required="" min="1" %}
                            </div>
							<div class="col-md-6 form-group">
                                <label for="">Select Size</label>
                                {% render_field form.sizes type="number" placeholder="Quantity" class="form-control" required="" min="1" %}
                            </div>
							<div class="col-md-12">
								<ul style="margin-bottom: 5px;">
									<li>Upload the <b>Zip Design</b>  that you Download From Previous Page</li>
								</ul>
							</div>
                            <div class="col-md-12 form-group">
                                <label for="">Upload Desing (.zip File)</label>
								{% render_field form.stuff type="file"  id="zipFileInput" accept=".zip" onchange="validateFileType(this)" class="form-control" required="" %}
                                <script>
                                    function validateFileType(input) {
                                        const allowedExtensions = ['zip'];
                                        const file = input.files[0];
                                        const fileName = file.name.toLowerCase();
                                        const fileExtension = fileName.split('.').pop();
                                    
                                        if (!allowedExtensions.includes(fileExtension)) {
                                            alert('Please select a .zip file.');
                                            input.value = ''; // Clear the file input
                                        }
                                    }
                                    </script>
                            </div>
                        </div>

                       
                    </div>
                </div>


               
				<div class="col-md-12 col-sm-12 guest-login">
					<h4 class="checkout-subtitle">Billing Address</h4>
					<div class="row">
						<div class="form-row">
							<div class="col-md-6 form-group">
								<label for="">First Name</label>
                                {% render_field form.first_name type="text" placeholder="First Name" class="form-control" required="" %}
							</div>
							<div class="col-md-6 form-group">
								<label for="">Last Name</label>
                                {% render_field form.last_name type="text" placeholder="Last Name" class="form-control" required="" %}
							</div>
						</div>
						<div class="form-row">
							<div class="col-md-6 form-group">
								<label for="">Email</label>
                                {% render_field form.email type="text" placeholder="Email" class="form-control" required="" %}
							</div>
							<div class="col-md-6 form-group">
								<label for="">Phone Number <i style="font-weight:400 ;">(Add Whatsapp Number if Possible)</i></label>
                                {% render_field form.phone type="tel" placeholder="Phone Number" class="form-control" required="" %}
							</div>
						</div>
						<div class="form-row">
							<div class="col-md-6 form-group">
								<label for="">Address Line 1</label>
                                {% render_field form.address_line_1 type="text" placeholder="Address Line 1" class="form-control" required="" %}
							</div>
							<div class="col-md-6 form-group">
								<label for="">Address Line 2</label>
                                {% render_field form.address_line_2 type="text" placeholder="Address Line 2" class="form-control" required="" %}
							</div>
						</div>
						<div class="form-row">
							<div class="col-md-4 form-group">
								<label for="">City</label>
                                {% render_field form.city type="text" placeholder="City" class="form-control" required="" %}
							</div>
							<div class="col-md-4 form-group">
								<label for="">State</label>
                                {% render_field form.state type="text" placeholder="State" class="form-control" required="" %}
							</div>
							<div class="col-md-4 form-group">
								<label for="">Country</label>
                                {% render_field form.country type="text" placeholder="Country" class="form-control" required="" %}
							</div>
						</div>
						<div class="form-row">
							<div class="col-md-12 form-group">
								<label for="">Order Note</label>
                                {% render_field form.order_note  %}
								<!-- <textarea name="order_note" rows="2" class="form-control"></textarea> -->
							</div>
						</div>
					</div>
					

					
				</div>
				<!-- guest-login -->

					

			</div>			
		</div>
		<!-- panel-body  -->

	</div><!-- row -->
</div>
<!-- checkout-step-06  -->
					  	
					</div><!-- /.checkout-steps -->
				</div>
<div class="col-xs-12 col-sm-6 col-md-6 sidebar">
					<!-- checkout-progress-sidebar -->
<div class="checkout-progress-sidebar ">
	<div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-heading">
		    	<h4 class="unicase-checkout-title">Your Checkout Progress</h4>
		    </div>
		    <div class="">
				<ul class="nav nav-checkout-progress list-unstyled">
					
						<li>
							<div class="cart-sub-total">
								Subtotal<span class="inner-left-md" style="font-weight: bold;float: right;" id="total-price">0</span>
							</div>
							<div class="cart-sub-total">
								Tax<span class="inner-left-md" style="font-weight: bold;float: right;" id="tax">0</span>
							</div>
							<div class="cart-grand-total">
								Grand Total<span class="inner-left-md" style="font-weight: bold;float: right;" id="total-amount-with-tax">0</span>
							</div>


						</li>
						<hr>
						
						<li>
							<div class="text-center">
							

							  

								<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
								  <i class="fa fa-institution"></i> Pay Now
								  </button>


								  <button type="submit"  style="margin-top: 10px;" class="btn btn-primary">
									  <i class="fa fa-money"></i> Cash On Delivery
									</button>
							  </div>
							
							<!-- Modal -->
							<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							  <div class="modal-dialog modal-dialog-centered">
								<div class="modal-content">
								  <div class="modal-header">
									<h5 class="modal-title" id="exampleModalLabel">Check Out</h5>
								   
								  </div>
								  <div class="modal-body" style="display: flex;justify-content: center;align-items: center;">
									  <div style="text-align: center;">
										  
										  <div>
											  <h4>Bank Details: </h4>
											  <h5>Name: WASEEM INTERNATIONAL</h5>
											  <h5>Bank Name: Meezan Bank-Liaqat Abad Branch - Faisalabad</h5>
											  <h5>Account Number: 04300109456940</h5>
											  <h5>IBAN: PK97MEZN0004300109456940</h5>
											  
											  <a href="https://wa.me/923016543034" style="font-size: 18px;" target="_blank"><i class="fa fa-whatsapp"></i> Send Payment Receipt</a>
											  <p>Sent Money in Our Bank Account and Sent Us Invoice in Our Whatsapp Number</p>
											  
											  <button type="submit" class="btn btn-primary"> <i class='fa fa-thumbs-o-up fa-lg'></i> Payment Done</button>
										  </div>	
										  <div>
											  <p class="" style="color: red;"> <b> Note! </b>COD is not available Out of Pakistan!</p>
										  </div>
									  </div>

								  </div>
								  <div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
									<!-- <button type="button" class="btn btn-primary">Save changes</button> -->
								  </div>
								</div>
							  </div>
							</div>
							
								
						</li>
				
					
				</ul>		
			</div>
		</div>
	</div>
</div> 
<!-- checkout-progress-sidebar -->				</div>
			</div><!-- /.row -->
		</div><!-- /.checkout-box -->


		</form>
</div>


{% include "includes/footer.html" %}



<script src="{% static 'assets/js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-hover-dropdown.min.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/echo.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.easing-1.3.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-slider.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.rateit.min.js' %}"></script>
<script src="{% static 'assets/js/lightbox.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>


$(document).ready(function() {
    $('#id_quantity').val(0);

    $('#id_quantity').change(function() {
        var quantity = $(this).val();
        var productId = "{{ product.id }}";
        $.ajax({
            url: "{% url 'calculate_total_price' %}",
            data: {
                'product_id': productId,
                'quantity': quantity
            },
            dataType: 'json',
            success: function(data) {
                var totalPrice = parseFloat(data.total_price).toFixed(0);
                var totalAmountWithTax = parseFloat(data.total_amount_with_tax).toFixed(2);
                var tax = parseFloat(data.tax).toFixed(0);

                $('#total-price').text(`${totalPrice} PKR`);
                $('#tax').text(`${tax} PKR`);
                $('#total-amount-with-tax').text(`${totalAmountWithTax} PKR`);
            }
        });
    });

    // $('form').submit(function(e) {
    //     var quantity = $('#id_quantity').val();
    //     if (quantity <= 0) {
    //         alert('Quantity must be 1 or greater.');
    //         e.preventDefault(); 
    //     }
    // });
});




</script>
</body>

</html>